package md.esempla.webflux.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostStatusAllPropertiesEquals(PostStatus expected, PostStatus actual) {
        assertPostStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertPostStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostStatusAllUpdatablePropertiesEquals(PostStatus expected, PostStatus actual) {
        assertPostStatusUpdatableFieldsEquals(expected, actual);
        assertPostStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostStatusAutoGeneratedPropertiesEquals(PostStatus expected, PostStatus actual) {
        assertThat(actual)
            .as("Verify PostStatus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostStatusUpdatableFieldsEquals(PostStatus expected, PostStatus actual) {
        assertThat(actual)
            .as("Verify PostStatus relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostStatusUpdatableRelationshipsEquals(PostStatus expected, PostStatus actual) {
        // empty method
    }
}
